# Generated by Django 4.2.4 on 2023-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_surfitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='product/mobile')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
