# Generated by Django 4.2.4 on 2023-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='selling_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
