# Generated by Django 4.2.4 on 2023-09-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_items_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='selling_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surfitems',
            name='selling_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
