# Generated by Django 4.2.4 on 2023-09-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
