# Generated by Django 4.2.4 on 2023-09-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_itemmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
    ]
