# Generated by Django 4.2.4 on 2023-09-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_order_id_itemmodel_razorpay_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemModel',
        ),
    ]
